### ISSUE TITLE
bulk insert 질문이 있습니다

### ISSUE THREAD

**Issue by jeongmin-bak** [continue-yeti/Yeti-backend#20]
## Description
sortedset bulk를 구현하셨다고 했는데 controller에는 list만 남아있습니다. 확인 부탁드립니다.

## To-do
- [ ] bulkinsert sortedset 추가

**Comment by honge7694** [comment]
확인 완료했고, PR 신청하였습니다. 문제 있는 코드 확인 부탁드립니다.
